### ISSUE TITLE
csvlint reports validation error

### ISSUE THREAD

**Issue by xrotwang** [edsu/csvw-template#1]
Unfortunately (mostly due to GitHub delivering the raw file as `text/plain`), the csv doesn't validate at [csvlint.io](http://csvlint.io/validation/5538a8bb63737617e40e0000).
It may well be, that csvlint doesn't implement the latest and greatest in metadata discovery, though.

**Comment by edsu** [comment]
Looks to me like it should be coming back text/csv now. I'm not sure if this helps csvlint or not since it seems unresponsive at the moment.
